image: starefossen/ruby-node

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
  - bundle exec jekyll build
  - mv _site public
  artifacts:
    paths:
    - public
  only:
  - master

cache:
  paths:
    - _site/
    - node_modules/

before_script:
  - ruby -v
  - npm -v
  - npm install
  - bundle -v
  - bundle install